name: Create_Release
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      version:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Version number'
        # Default value if no value is explicitly provided
        default: '0.0.0'
        # Input has to be provided for the workflow to run
        required: true
jobs:
  create-release-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.CI_PERSONAL_TOKEN }}
          fetch-depth: 0
          ref: 'dev'

      - name: Setup Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: '3.9'

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.PRIVATE_KEY_CI }}
          passphrase: ${{ secrets.PASSWORD_KEY_CI }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Bump versions
        run: python3 bumpversion.py ${{ github.event.inputs.version }}

      - name: Set environment variables
        run: |
          echo "NEW_BRANCH_NAME=release/v${{ github.event.inputs.version }}" >> $GITHUB_ENV

      - name: Commit changes
        run: |
          git config --global user.name ${{ secrets.CI_USERNAME }}
          git config --global user.email ${{ secrets.CI_EMAIL }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4.0.1
        with:
          token: ${{ secrets.CI_PERSONAL_TOKEN }}
          committer: ${{ secrets.CI_USERNAME }} <${{ secrets.CI_EMAIL }}>
          author: ${{ secrets.CI_USERNAME }} <${{ secrets.CI_EMAIL }}>
          commit-message: 'chore: bump version to ${{ github.event.inputs.version }}'
          branch: ${{ env.NEW_BRANCH_NAME }}
          delete-branch: true
          base: 'main'
          title: 'Release v${{ github.event.inputs.version }}'
          body: 'TODO'
          labels: 'release'
          reviewers: 'hoersamu'
          assignees: 'hoersamu'
